import { ICssValueGroup } from '@interfaces';

export const CSS_PROPERTIES: string[] = [
    // Layout / display
    'display', 'visibility', 'content-visibility', 'position', 'top', 'right', 'bottom', 'left', 'inset',
    'inset-block', 'inset-block-start', 'inset-block-end', 'inset-inline', 'inset-inline-start', 'inset-inline-end',
    'z-index', 'float', 'clear', 'overflow', 'overflow-x', 'overflow-y', 'overflow-anchor', 'overflow-wrap',
    'overscroll-behavior', 'overscroll-behavior-x', 'overscroll-behavior-y', 'isolation', 'contain', 'aspect-ratio',
    // Box model
    'width', 'min-width', 'max-width', 'height', 'min-height', 'max-height',
    'block-size', 'min-block-size', 'max-block-size', 'inline-size', 'min-inline-size', 'max-inline-size',
    'margin', 'margin-top', 'margin-right', 'margin-bottom', 'margin-left',
    'margin-block', 'margin-block-start', 'margin-block-end', 'margin-inline', 'margin-inline-start', 'margin-inline-end',
    'padding', 'padding-top', 'padding-right', 'padding-bottom', 'padding-left',
    'padding-block', 'padding-block-start', 'padding-block-end', 'padding-inline', 'padding-inline-start', 'padding-inline-end',
    'box-sizing', 'box-shadow', 'box-decoration-break',
    // Border / outline
    'border', 'border-width', 'border-style', 'border-color',
    'border-top', 'border-top-width', 'border-top-style', 'border-top-color',
    'border-right', 'border-right-width', 'border-right-style', 'border-right-color',
    'border-bottom', 'border-bottom-width', 'border-bottom-style', 'border-bottom-color',
    'border-left', 'border-left-width', 'border-left-style', 'border-left-color',
    'border-block', 'border-block-start', 'border-block-end', 'border-inline', 'border-inline-start', 'border-inline-end',
    'border-radius', 'border-top-left-radius', 'border-top-right-radius', 'border-bottom-right-radius', 'border-bottom-left-radius',
    'border-start-start-radius', 'border-start-end-radius', 'border-end-start-radius', 'border-end-end-radius',
    'border-image', 'border-image-source', 'border-image-slice', 'border-image-width', 'border-image-outset', 'border-image-repeat',
    'border-collapse', 'border-spacing',
    'outline', 'outline-width', 'outline-style', 'outline-color', 'outline-offset',
    // Flexbox
    'flex', 'flex-grow', 'flex-shrink', 'flex-basis', 'flex-direction', 'flex-wrap', 'flex-flow', 'order',
    // Grid
    'grid', 'grid-template', 'grid-template-columns', 'grid-template-rows', 'grid-template-areas',
    'grid-auto-columns', 'grid-auto-rows', 'grid-auto-flow',
    'grid-area', 'grid-column', 'grid-column-start', 'grid-column-end', 'grid-row', 'grid-row-start', 'grid-row-end',
    // Alignment / gap
    'align-content', 'align-items', 'align-self', 'justify-content', 'justify-items', 'justify-self',
    'place-content', 'place-items', 'place-self', 'gap', 'row-gap', 'column-gap', 'vertical-align',
    // Typography
    'font', 'font-family', 'font-size', 'font-size-adjust', 'font-style', 'font-weight', 'font-stretch',
    'font-variant', 'font-variant-caps', 'font-variant-numeric', 'font-variant-ligatures', 'font-feature-settings',
    'font-variation-settings', 'font-kerning', 'font-optical-sizing', 'font-display',
    'line-height', 'letter-spacing', 'word-spacing', 'text-align', 'text-align-last', 'text-indent',
    'text-decoration', 'text-decoration-line', 'text-decoration-style', 'text-decoration-color', 'text-decoration-thickness',
    'text-underline-offset', 'text-underline-position', 'text-transform', 'text-shadow', 'text-overflow', 'text-wrap',
    'text-orientation', 'text-rendering', 'white-space', 'word-break', 'word-wrap', 'hyphens', 'tab-size',
    'writing-mode', 'direction', 'unicode-bidi', 'quotes', 'line-break', 'ruby-position', 'hanging-punctuation',
    // Color / background
    'color', 'accent-color', 'caret-color', 'color-scheme', 'opacity',
    'background', 'background-color', 'background-image', 'background-position', 'background-position-x', 'background-position-y',
    'background-size', 'background-repeat', 'background-origin', 'background-clip', 'background-attachment', 'background-blend-mode',
    'mix-blend-mode', 'backdrop-filter', 'filter',
    // Lists / counters / tables
    'list-style', 'list-style-type', 'list-style-position', 'list-style-image',
    'counter-reset', 'counter-increment', 'counter-set',
    'table-layout', 'caption-side', 'empty-cells',
    // Transform / transition / animation
    'transform', 'transform-origin', 'transform-style', 'transform-box', 'translate', 'rotate', 'scale',
    'perspective', 'perspective-origin', 'backface-visibility',
    'transition', 'transition-property', 'transition-duration', 'transition-timing-function', 'transition-delay', 'transition-behavior',
    'animation', 'animation-name', 'animation-duration', 'animation-timing-function', 'animation-delay',
    'animation-iteration-count', 'animation-direction', 'animation-fill-mode', 'animation-play-state', 'animation-composition',
    'will-change', 'offset', 'offset-path', 'offset-distance', 'offset-rotate', 'offset-anchor',
    // Interaction / UI
    'cursor', 'pointer-events', 'user-select', 'touch-action', 'resize', 'appearance',
    'scroll-behavior', 'scroll-margin', 'scroll-padding', 'scroll-snap-type', 'scroll-snap-align', 'scroll-snap-stop',
    'scrollbar-color', 'scrollbar-width', 'scrollbar-gutter',
    // Masking / clipping / shapes
    'clip-path', 'mask', 'mask-image', 'mask-mode', 'mask-position', 'mask-size', 'mask-repeat', 'mask-origin', 'mask-clip', 'mask-composite',
    'shape-outside', 'shape-margin', 'shape-image-threshold', 'object-fit', 'object-position',
    // Columns / fragmentation
    'columns', 'column-count', 'column-width', 'column-gap', 'column-rule', 'column-rule-width', 'column-rule-style',
    'column-rule-color', 'column-span', 'column-fill', 'break-before', 'break-inside', 'break-after', 'orphans', 'widows',
    // Misc
    'all', 'container', 'container-type', 'container-name', 'zoom', 'image-rendering', 'paint-order',
    'forced-color-adjust', 'print-color-adjust', 'view-transition-name',
];
export const CSS_VALUES: ICssValueGroup[] = [
    { properties: ['*'], values: ['inherit', 'initial', 'unset', 'revert', 'revert-layer'] },
    { properties: ['display'], values: [
        'block', 'inline', 'inline-block', 'flex', 'inline-flex', 'grid', 'inline-grid',
        'flow-root', 'table', 'table-row', 'table-cell', 'list-item', 'contents', 'none',
    ] },
    { properties: ['position'], values: ['static', 'relative', 'absolute', 'fixed', 'sticky'] },
    { properties: ['visibility'], values: ['visible', 'hidden', 'collapse'] },
    { properties: ['overflow', 'overflow-x', 'overflow-y'], values: ['visible', 'hidden', 'clip', 'scroll', 'auto'] },
    { properties: ['box-sizing'], values: ['content-box', 'border-box'] },
    { properties: ['float'], values: ['left', 'right', 'inline-start', 'inline-end', 'none'] },
    { properties: ['clear'], values: ['left', 'right', 'both', 'inline-start', 'inline-end', 'none'] },
    { properties: ['isolation'], values: ['auto', 'isolate'] },
    { properties: [
        'width', 'min-width', 'max-width', 'height', 'min-height', 'max-height',
        'block-size', 'inline-size', 'flex-basis',
    ], values: ['auto', 'min-content', 'max-content', 'fit-content', '100%'] },
    { properties: ['aspect-ratio'], values: ['auto', '1 / 1', '4 / 3', '16 / 9'] },
    { properties: ['margin', 'margin-top', 'margin-right', 'margin-bottom', 'margin-left', 'z-index'], values: ['auto', '0'] },
    { properties: [
        'border-style', 'border-top-style', 'border-right-style', 'border-bottom-style', 'border-left-style', 'outline-style',
        'column-rule-style',
    ], values: ['none', 'hidden', 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset'] },
    { properties: [
        'color', 'background-color', 'border-color', 'border-top-color', 'border-right-color', 'border-bottom-color',
        'border-left-color', 'outline-color', 'text-decoration-color', 'caret-color', 'accent-color', 'column-rule-color',
    ], values: ['currentColor', 'transparent'] },
    { properties: ['flex-direction'], values: ['row', 'row-reverse', 'column', 'column-reverse'] },
    { properties: ['flex-wrap'], values: ['nowrap', 'wrap', 'wrap-reverse'] },
    { properties: ['justify-content', 'align-content', 'place-content'], values: [
        'flex-start', 'flex-end', 'center', 'space-between', 'space-around', 'space-evenly', 'start', 'end', 'stretch',
    ] },
    { properties: ['align-items', 'align-self', 'justify-items', 'justify-self', 'place-items', 'place-self'], values: [
        'flex-start', 'flex-end', 'center', 'baseline', 'stretch', 'start', 'end', 'self-start', 'self-end',
    ] },
    { properties: ['grid-auto-flow'], values: ['row', 'column', 'dense', 'row dense', 'column dense'] },
    { properties: ['font-style'], values: ['normal', 'italic', 'oblique'] },
    { properties: ['font-weight'], values: ['normal', 'bold', 'lighter', 'bolder', '100', '200', '300', '400', '500', '600', '700', '800', '900'] },
    { properties: ['font-family'], values: ['system-ui', 'sans-serif', 'serif', 'monospace', 'cursive', 'fantasy'] },
    { properties: ['line-height', 'letter-spacing', 'word-spacing'], values: ['normal'] },
    { properties: ['text-align', 'text-align-last'], values: ['left', 'right', 'center', 'justify', 'start', 'end'] },
    { properties: ['text-transform'], values: ['none', 'capitalize', 'uppercase', 'lowercase'] },
    { properties: ['text-decoration', 'text-decoration-line'], values: ['none', 'underline', 'overline', 'line-through'] },
    { properties: ['text-decoration-style'], values: ['solid', 'double', 'dotted', 'dashed', 'wavy'] },
    { properties: ['text-overflow'], values: ['clip', 'ellipsis'] },
    { properties: ['text-wrap'], values: ['wrap', 'nowrap', 'balance', 'pretty'] },
    { properties: ['white-space'], values: ['normal', 'nowrap', 'pre', 'pre-wrap', 'pre-line', 'break-spaces'] },
    { properties: ['word-break'], values: ['normal', 'break-all', 'keep-all', 'break-word'] },
    { properties: ['overflow-wrap', 'word-wrap'], values: ['normal', 'break-word', 'anywhere'] },
    { properties: ['hyphens'], values: ['none', 'manual', 'auto'] },
    { properties: ['direction'], values: ['ltr', 'rtl'] },
    { properties: ['writing-mode'], values: ['horizontal-tb', 'vertical-rl', 'vertical-lr'] },
    { properties: ['vertical-align'], values: ['baseline', 'top', 'middle', 'bottom', 'text-top', 'text-bottom', 'sub', 'super'] },
    { properties: ['background-repeat'], values: ['repeat', 'repeat-x', 'repeat-y', 'no-repeat', 'space', 'round'] },
    { properties: ['background-size'], values: ['auto', 'cover', 'contain'] },
    { properties: ['background-position'], values: ['center', 'top', 'right', 'bottom', 'left', 'top left', 'top right', 'bottom left', 'bottom right'] },
    { properties: ['background-attachment'], values: ['scroll', 'fixed', 'local'] },
    { properties: ['background-clip', 'background-origin'], values: ['border-box', 'padding-box', 'content-box', 'text'] },
    { properties: ['mix-blend-mode', 'background-blend-mode'], values: [
        'normal', 'multiply', 'screen', 'overlay', 'darken', 'lighten', 'color-dodge', 'color-burn',
        'hard-light', 'soft-light', 'difference', 'exclusion', 'hue', 'saturation', 'color', 'luminosity',
    ] },
    { properties: ['object-fit'], values: ['fill', 'contain', 'cover', 'none', 'scale-down'] },
    { properties: ['list-style-type'], values: ['none', 'disc', 'circle', 'square', 'decimal', 'decimal-leading-zero', 'lower-alpha', 'upper-alpha', 'lower-roman', 'upper-roman'] },
    { properties: ['list-style-position'], values: ['inside', 'outside'] },
    { properties: ['border-collapse'], values: ['collapse', 'separate'] },
    { properties: ['table-layout'], values: ['auto', 'fixed'] },
    { properties: ['caption-side'], values: ['top', 'bottom'] },
    { properties: ['empty-cells'], values: ['show', 'hide'] },
    { properties: ['transition-timing-function', 'animation-timing-function'], values: [
        'ease', 'linear', 'ease-in', 'ease-out', 'ease-in-out', 'step-start', 'step-end',
    ] },
    { properties: ['animation-direction'], values: ['normal', 'reverse', 'alternate', 'alternate-reverse'] },
    { properties: ['animation-fill-mode'], values: ['none', 'forwards', 'backwards', 'both'] },
    { properties: ['animation-play-state'], values: ['running', 'paused'] },
    { properties: ['animation-iteration-count'], values: ['infinite', '1'] },
    { properties: ['transform', 'filter', 'backdrop-filter', 'box-shadow', 'text-shadow', 'clip-path'], values: ['none'] },
    { properties: ['will-change'], values: ['auto', 'transform', 'opacity', 'scroll-position', 'contents'] },
    { properties: ['cursor'], values: [
        'auto', 'default', 'pointer', 'wait', 'progress', 'text', 'move', 'grab', 'grabbing', 'crosshair',
        'not-allowed', 'help', 'zoom-in', 'zoom-out', 'col-resize', 'row-resize', 'ew-resize', 'ns-resize', 'none',
    ] },
    { properties: ['pointer-events'], values: ['auto', 'none'] },
    { properties: ['user-select'], values: ['auto', 'none', 'text', 'all'] },
    { properties: ['touch-action'], values: ['auto', 'none', 'pan-x', 'pan-y', 'manipulation', 'pinch-zoom'] },
    { properties: ['resize'], values: ['none', 'both', 'horizontal', 'vertical'] },
    { properties: ['appearance'], values: ['none', 'auto'] },
    { properties: ['scroll-behavior'], values: ['auto', 'smooth'] },
    { properties: ['scroll-snap-type'], values: ['none', 'x mandatory', 'y mandatory', 'x proximity', 'y proximity', 'both mandatory'] },
    { properties: ['scroll-snap-align'], values: ['none', 'start', 'end', 'center'] },
    { properties: ['scrollbar-width'], values: ['auto', 'thin', 'none'] },
    { properties: ['scrollbar-gutter'], values: ['auto', 'stable', 'stable both-edges'] },
    { properties: ['overscroll-behavior', 'overscroll-behavior-x', 'overscroll-behavior-y'], values: ['auto', 'contain', 'none'] },
    { properties: ['color-scheme'], values: ['normal', 'light', 'dark', 'light dark'] },
    { properties: ['content-visibility'], values: ['visible', 'auto', 'hidden'] },
    { properties: ['contain'], values: ['none', 'strict', 'content', 'size', 'layout', 'style', 'paint'] },
    { properties: ['container-type'], values: ['normal', 'size', 'inline-size'] },
    { properties: ['break-before', 'break-after'], values: ['auto', 'avoid', 'always', 'page', 'column'] },
    { properties: ['break-inside'], values: ['auto', 'avoid', 'avoid-page', 'avoid-column'] },
    { properties: ['image-rendering'], values: ['auto', 'crisp-edges', 'pixelated'] },
];
export function getCssValues(property: string): string[] {
    return CSS_VALUES
        .filter(({ properties }) => properties.includes(property) || properties.includes('*'))
        .flatMap(({ values }) => values);
}
